api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    graphql:
        graphiql:
            enabled: true
        nesting_separator: _


doctrine:
    orm:
        filters:
            user_filter:
                class: App\Filter\UserFilter