#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

api_graphql_entrypoint:
    path: /apiql/graphql
    controller: api_platform.graphql.action.entrypoint